//
// Created by nidzo on 2/1/24.
//

#include "common.h"

// patterns generated by the python tool
#include "patterns_gen.h"

#pragma code-name ("CODE_B0")
#pragma rodata-name ("RODATA_B0")

PATTERN_TABLE_DEFINITION;

#pragma bss-name(push, "OAMBSS")
struct Sprite oam[64];
#pragma bss-name(pop)

unsigned char ppu_ready = 0;
volatile unsigned char blanked = 0;

void writeoam()
{
    for(zpb1=0; zpb1<64;++zpb1)
    {
        oam[zpb1].attributes = 0;
        oam[zpb1].x=oam[zpb1].y=255;
    }

    oam[0].x=128;
    oam[0].y=120;
    oam[0].tile=TILE_MOUSE_0_0;
    oam[0].attributes = 0x00;
}

void flush_oam()
{
    OAMADDR = 0x00;
    OAMDMA = 0x02;
    OAMADDR = 0x00;
}

void wait_for_ppu_ready_and_disable()
{
    zpb1=PPUSTATUS;
    while(!(PPUSTATUS&128))
    {

    }
    while(!(PPUSTATUS&128))
    {

    }
    PPUCTRL = 0;
    PPUMASK = 0;
    while(!(PPUSTATUS&128))
    {

    }
    while(!(PPUSTATUS&128))
    {

    }

    zpb1 = PPUSTATUS;
}

void reenable_ppu()
{
    zpb1 = PPUSTATUS;
    PPUSCROLL = 0x00;
    PPUSCROLL = 0x00;
    PPUMASK = 0x9E;
    PPUCTRL = 0x80;
}


void ppu_init()
{
    const unsigned char *pattern_ptr;

    wait_for_ppu_ready_and_disable();

    PPUADDR = 0x00;
    PPUADDR = 0x00;

    // Fill the pattern table
    pattern_ptr = pattern_table_content;
    zpw1 = PATTERN_TABLE_LENGTH;
    while(zpw1--)
    {
        PPUDATA = *pattern_ptr;
        ++pattern_ptr;
    }

    PPUADDR = 0x20;
    PPUADDR = 0x00;

    // wallpaper
    for(zpb1=0;zpb1<28;++zpb1)
    {
        for(zpb2=0;zpb2<32;++zpb2)
        {
            PPUDATA = TILE_WALLPAPER_0_0;
        }
    }

    // taskbar
    for(zpb1=0;zpb1<2;++zpb1)
    {
        // start menu
        if(zpb1)
        {
            PPUDATA = TILE_START_1_0;
            PPUDATA = TILE_START_1_1;
        }
        else
        {
            PPUDATA = TILE_START_0_0;
            PPUDATA = TILE_START_0_1;
        }

        // search bar
        for(zpb2=0;zpb2<6;++zpb2)
        {
            PPUDATA = TILE_SEARCHBAR_0_0;
        }
        if(zpb1)
        {
            PPUDATA = TILE_CORTANA_1_0;
            PPUDATA = TILE_CORTANA_1_1;
        }
        else
        {
            PPUDATA = TILE_CORTANA_0_0;
            PPUDATA = TILE_CORTANA_0_1;
        }

        // empty part
        for(zpb2=0;zpb2<17;++zpb2)
        {
            PPUDATA = TILE_TASKBAR_0_0;
        }

        // clock
        if(zpb1)
        {
            PPUDATA = TILE_CLOCK_1_0;
            PPUDATA = TILE_CLOCK_1_1;
            PPUDATA = TILE_CLOCK_1_2;
            PPUDATA = TILE_CLOCK_1_3;
        }
        else
        {
            PPUDATA = TILE_CLOCK_0_0;
            PPUDATA = TILE_CLOCK_0_1;
            PPUDATA = TILE_CLOCK_0_2;
            PPUDATA = TILE_CLOCK_0_3;
        }
        PPUDATA = TILE_TASKBAR_0_0;
    }

    PPUADDR = 0x20;
    PPUADDR = 0x42;
    PPUDATA = TILE_THISPC_0_0;
    PPUDATA = TILE_THISPC_0_1;
    PPUDATA = TILE_THISPC_0_2;
    PPUDATA = TILE_THISPC_0_3;
    PPUADDR = 0x20;
    PPUADDR = 0x62;
    PPUDATA = TILE_THISPC_1_0;
    PPUDATA = TILE_THISPC_1_1;
    PPUDATA = TILE_THISPC_1_2;
    PPUDATA = TILE_THISPC_1_3;
    PPUADDR = 0x20;
    PPUADDR = 0x82;
    PPUDATA = TILE_THISPC_2_0;
    PPUDATA = TILE_THISPC_2_1;
    PPUDATA = TILE_THISPC_2_2;
    PPUDATA = TILE_THISPC_2_3;
    PPUADDR = 0x20;
    PPUADDR = 0xa2;
    PPUDATA = TILE_THISPC_3_0;
    PPUDATA = TILE_THISPC_3_1;
    PPUDATA = TILE_THISPC_3_2;
    PPUDATA = TILE_THISPC_3_3;

    PPUADDR = 0x22;
    PPUADDR = 0xda;
    PPUDATA = TILE_TRASH_0_0;
    PPUDATA = TILE_TRASH_0_1;
    PPUDATA = TILE_TRASH_0_2;
    PPUDATA = TILE_TRASH_0_3;
    PPUADDR = 0x22;
    PPUADDR = 0xfa;
    PPUDATA = TILE_TRASH_1_0;
    PPUDATA = TILE_TRASH_1_1;
    PPUDATA = TILE_TRASH_1_2;
    PPUDATA = TILE_TRASH_1_3;
    PPUADDR = 0x23;
    PPUADDR = 0x1a;
    PPUDATA = TILE_TRASH_2_0;
    PPUDATA = TILE_TRASH_2_1;
    PPUDATA = TILE_TRASH_2_2;
    PPUDATA = TILE_TRASH_2_3;
    PPUADDR = 0x23;
    PPUADDR = 0x3a;
    PPUDATA = TILE_TRASH_3_0;
    PPUDATA = TILE_TRASH_3_1;
    PPUDATA = TILE_TRASH_3_2;
    PPUDATA = TILE_TRASH_3_3;

    PPUADDR = 0x23;
    PPUADDR = 0xC0;
    // background attributes
    for(zpb1=0;zpb1<7;++zpb1)
    {
        for(zpb2=0;zpb2<8;++zpb2)
        {
            PPUDATA = 0x00;
        }
    }
    // taskbar attributes
    for(zpb2=0;zpb2<8;++zpb2)
    {
        PPUDATA = 0x05;
    }

    PPUADDR = 0x23;
    PPUADDR = 0xee;
    PPUDATA = 0xaa;
    PPUDATA = 0xaa;
    PPUADDR = 0x23;
    PPUADDR = 0xf6;
    PPUDATA = 0xaa;
    PPUDATA = 0xaa;

    PPUADDR = 0x3f;
    PPUADDR = 0x00;

    // wallpaper tile palette
    // 0x3f00
    PPUDATA = 0x21; // background
    PPUDATA = 0x20; // white
    PPUDATA = 0x2d; // grey
    PPUDATA = 0x21; // icon background

    // taskbar tile empty palette
    // 0x3f04
    PPUDATA = 0x21; // bg
    PPUDATA = 0x20; // white
    PPUDATA = 0x0c; // darkblue
    PPUDATA = 0x1c; //lightblue

    // trash icon palette
    // 0x3f08
    PPUDATA = 0x21; // background
    PPUDATA = 0x20; // white
    PPUDATA = 0x2d; // grey
    PPUDATA = 0x21; // icon background

    // mouse palette
    PPUADDR = 0x3f;
    PPUADDR = 0x11;
    PPUDATA = 0x0e;
    PPUDATA = 0x20;
    PPUDATA = 0x0e;

    writeoam();
    flush_oam();

    ppu_ready = 1;
    reenable_ppu();
}
